#!/usr/bin/env python3
"""Generate open-firenet/web_ui.h from open-firenet/web/index.html.

The page is stored gzip-compressed in flash and served with "Content-Encoding: gzip"
(every browser decompresses it), which takes about a quarter of the room of the plain
text. Edit web/index.html, then run this script and commit both files.

  python3 tools/gen_web_ui.py          # regenerate web_ui.h
  python3 tools/gen_web_ui.py --check  # exit 1 if web_ui.h is out of date (CI)
"""
import gzip
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent / "open-firenet"
SRC = ROOT / "web" / "index.html"
OUT = ROOT / "web_ui.h"


def render() -> str:
    html = SRC.read_bytes()
    gz = gzip.compress(html, compresslevel=9, mtime=0)  # mtime=0: same input -> same bytes
    lines = []
    for i in range(0, len(gz), 20):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")
    return (
        "#pragma once\n"
        "#include <pgmspace.h>\n\n"
        "// GENERATED by tools/gen_web_ui.py from web/index.html -- do not edit by hand.\n"
        f"// Web UI, gzip-compressed: {len(html)} bytes of HTML stored as {len(gz)} bytes.\n"
        f"static const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != content:
            print(f"{OUT} is out of date: run python3 tools/gen_web_ui.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
