#!/usr/bin/env python3
"""Generate open-firenet/web_ui.h from open-firenet/web/index.html.

The page is stored gzip-compressed in flash and served with "Content-Encoding: gzip"
(every browser decompresses it), which takes about a quarter of the room of the plain
text. Edit web/index.html, then run this script and commit both files.

  python3 tools/gen_web_ui.py          # regenerate web_ui.h
  python3 tools/gen_web_ui.py --check  # exit 1 if web_ui.h is out of date (CI)
"""
import gzip
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent / "open-firenet"
SRC = ROOT / "web" / "index.html"
OUT = ROOT / "web_ui.h"


def render() -> str:
    html = SRC.read_bytes()
    gz = gzip.compress(html, compresslevel=9, mtime=0)  # mtime=0: same input -> same bytes
    # Byte 9 of the gzip header names the system that compressed the data: Python 3.11 writes 3 (Unix), Python 3.13
    # writes 255 (unknown). Fixed here, so that the file does not depend on the Python version that generated it.
    gz = gz[:9] + b"\x03" + gz[10:]
    lines = []
    for i in range(0, len(gz), 20):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")
    return (
        "#pragma once\n"
        "#include <pgmspace.h>\n\n"
        "// GENERATED by tools/gen_web_ui.py from web/index.html -- do not edit by hand.\n"
        f"// Web UI, gzip-compressed: {len(html)} bytes of HTML stored as {len(gz)} bytes.\n"
        f"static const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def embedded_page(header: str):
    """The page stored in a web_ui.h, decompressed; None if the file is not a consistent web_ui.h."""
    try:
        declared = int(re.search(r"INDEX_HTML_GZ_LEN = (\d+);", header).group(1))
        body = header[header.index("INDEX_HTML_GZ[]"):]
        gz = bytes(int(x, 16) for x in re.findall(r"0x([0-9a-f]{2})", body))
        return gzip.decompress(gz) if len(gz) == declared else None
    except (AttributeError, ValueError, OSError, EOFError):
        return None


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        # What matters is the page the firmware will serve: the committed bytes are decompressed and compared with
        # index.html, so that a different zlib (another compressed form of the same page) is not reported as stale.
        if not OUT.exists() or embedded_page(OUT.read_text()) != SRC.read_bytes():
            print(f"{OUT} is out of date: run python3 tools/gen_web_ui.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
